server:
  port: 8888
spring:
  application:
    name: RentaCar
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true