server:
  port: 8888
  ssl:
    enabled: false
spring:
  application:
    name: RentaCar
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
springdoc:
  api-docs:
    path: /docs
    pathsToMatch: /api/**
  swagger-ui:
    use-root-path: true
    #disable-swagger-default-url: true
    path: /docs-ui